language: csharp

sudo: required

mono: none

dist: trusty

dotnet: 1.0.3
  
before_script:
  pwd
  - dotnet --info
  - dotnet restore /src/PushoverNet/PushoverNet.csproj

script:
  - dotnet build /src/PushoverNet/PushoverNet.csproj
