language: csharp

sudo: required

mono: none

dist: trusty

dotnet: 1.0.4
  
before_script:
  - pwd
  - dotnet restore src/PushoverNet/PushoverNet.csproj
  - dotnet restore test/PushoverNet.Test/PushoverNet.Test.csproj

script:
  - dotnet build src/PushoverNet/PushoverNet.csproj
  - dotnet test test/PushoverNet.Test/PushoverNet.Test.csproj
  - dotnet pack src/PushoverNet/PushoverNet.csproj --configuration Release
  
