version: 0.0.1.{build}

image: Visual Studio 2017

configuration: Release

platform: Any CPU

before_build:
  - dotnet --info
  - dotnet restore .\src\PushoverNet\PushoverNet.csproj
  
build:
  project: .\src\PushoverNet\PushoverNet.csproj
  verbosity: normal

after_build:
  - dotnet pack .\src\PushoverNet\PushoverNet.csproj --configuration Release
  
test_script:
  - dotnet restore .\test\PushoverNet.Test\PushoverNet.Test.csproj
  - dotnet test .\test\PushoverNet.Test\PushoverNet.Test.csproj --configuration Release --logger:trx;LogFileName=tests-results01.xml

artifacts:
  - path: '**\PushoverNet.*.nupkg' # find all NuGet packages recursively
